name: Build
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - uses: actions/setup-node@v4
        name: Setup Node
      - run: npm install
        name: Setup Dependencies
      - run: npx eleventy
        name: Build Files
      - uses: actions/upload-artifact@v4
        name: Upload Files
        with:
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Output Repository
        with:
          ref: 'live'
          path: 'live'
      - run: ls -l
      - uses: actions/download-artifact@v4
        name: Download Files
      - run: git -C 'live' rm -r '*''
        name: Remove Old Files