name: Build
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - uses: actions/setup-node@v4
        name: Setup Node
      - run: npm install
        name: Setup Dependencies
      - run: npx eleventy
        name: Build Files
      - uses: actions/upload-artifact@v4
        name: Upload Files
        with:
          path: _site
          name: site.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Output Repository
        with:
          ref: 'live'
          path: 'live'
      - run: git config --global user.name 'github-actions[bot]' && git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: git rm -rf '*' || true
        name: Remove Old Files
        working-directory: 'live'
      - uses: actions/download-artifact@v4
        name: Download Files
        with:
          name: site.zip
          path: live
      - run: git add -A && git commit -m "Update" && git push
        working-directory: 'live'