name: Build and Deploy
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - uses: actions/setup-node@v4
        name: Setup Node
      - run: npm install
        name: Setup Dependencies
      - run: npx eleventy
        name: Build Files
        env:
          SITE_URL: '${{ vars.SITE_URL }}'
          SOURCE_URL: '${{ github.server_url }}/${{ github.repository }}/tree/${{ github.sha }}/'
          SOURCE_COMMIT: '${{ github.sha }}'
      - uses: actions/upload-pages-artifact@v3
        name: Upload Files
        with:
          path: _site
      - uses: actions/upload-artifact@v4
        name: Upload Files
        id: upload
        with:
          path: _site
          name: site
      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: site
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
  publish:
    concurrency: 
      group: 'publish'
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Output Repository
        with:
          ref: 'live'
          path: 'live'
      - run: git config --global user.name 'github-actions[bot]' && git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        name: Setup Git User
      - run: find . -type f -not -path './.git/*' -delete -print
        name: Remove Old Files
        working-directory: 'live'
      - uses: actions/download-artifact@v4
        name: Download Files
        with:
          name: site
          path: live
      - run: git add -A && git commit --allow-empty -m "[$COMMIT_ID] $COMMIT_MESSAGE" && git push
        working-directory: 'live'
        name: Commit Results
        env:
          COMMIT_ID: ${{ github.event.head_commit.id }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  deploy:
    concurrency: 
      group: 'deploy'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v4
        name: Download Files
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4